


#include <stdio.h>
int sum(int a);

int main()
{
    int a, c = 0;
    printf("type the number of terms you want to sum as given in the concept\n");
    scanf("%d", &a);
    c = sum(a);
    printf("the sum is %d\n", c);
    return 0;
}
int sum(int a)
{
    int sum, x = 1, i;
    for (i =1; i <= a; i++)
    {
        x = x * i;
        sum = sum + (x/i);
    }
    return sum;
}